<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

// List fonts
$faces = array(
    'Arial, Helvetica, sans-serif' => 'Arial',
    'Arial Black, Gadget, sans-serif' => 'Arial Black',
    'Comic Sans MS, cursive' => 'Comic Sans MS',
    'Courier New, monospace' => 'Courier New',
    'Georgia, serif' => 'Georgia',
    '"HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue",Helvetica, Arial, "Lucida Grande", sans-serif' => 'Helvetica Neue',
    'Impact, Charcoal, sans-serif' => 'Impact',
    'Lucida Console, Monaco, monospace' => 'Lucida Console',
    'Lucida Sans Unicode, Lucida Grande, sans-serif' => 'Lucida Sans Unicode',
    '"Open Sans", sans-serif' => 'Open Sans',
    'Palatino Linotype, Book Antiqua, Palatino, serif' => 'Palatino Linotype',
    'Tahoma, Geneva, sans-serif' => 'Tahoma',
    'Times New Roman, Times, serif' => 'Times New Roman',
    'Trebuchet MS, sans-serif' => 'Trebuchet MS',
    'Verdana, Geneva, sans-serif' => 'Verdana',
    'Symbol' => 'Symbol',
    'Webdings' => 'Webdings',
    'Wingdings, Zapf Dingbats' => 'Wingdings',
    'MS Sans Serif, Geneva, sans-serif' => 'MS Sans Serif',
    'MS Serif, New York, serif' => 'MS Serif',
    'Google Fonts' => 'Google Fonts',
);

$font_sizes_texts= array(
        '.3rem' => '.3',
        '.4rem' => '.4',
        '.5rem' => '.5',
        '.6rem' => '.6',
        '.7rem' => '.7',
        '.8rem' => '.8',
        '.9rem' => '.9',
        '1rem' => '1',
        '1.1rem' => '1.1',
        '1.2rem' => '1.2',
        '1.3rem' => '1.3',
        '1.4rem' => '1.4',
        '1.5rem' => '1.5',
        '1.6rem' => '1.6',
        '1.7rem' => '1.7',
        '1.8rem' => '1.8',
        '1.9rem' => '1.9',
        '2rem' => '2',
        '2.5rem' => '2.5',
        '3rem' => '3',
        '3.5rem' => '3.5',
        '4rem' => '4',
        '4.5rem' => '4.5',
        '5rem' => '5',
        '5.5rem' => '5.5',
        '6rem' => '6',
    );

$font_size_header= array(
        '1rem' => '1',
        '1.1rem' => '1.1',
        '1.2rem' => '1.2',
        '1.3rem' => '1.3',
        '1.4rem' => '1.4',
        '1.5rem' => '1.5',
        '1.6rem' => '1.6',
        '1.7rem' => '1.7',
        '1.8rem' => '1.8',
        '1.9rem' => '1.9',
        '2rem' => '2',
        '2.1rem' => '2.1',
        '2.2rem' => '2.2',
        '2.3rem' => '2.3',
        '2.4rem' => '2.4',
        '2.5rem' => '2.5',
        '2.6rem' => '2.6',
        '2.7rem' => '2.7',
        '2.8rem' => '2.8',
        '2.9rem' => '2.9',
        '3rem' => '3',
        '3.1rem' => '3.1',
        '3.2rem' => '3.2',
        '3.3rem' => '3.3',
        '3.4rem' => '3.4',
        '3.5rem' => '3.5',
        '3.6rem' => '3.6',
        '3.7rem' => '3.7',
        '3.8rem' => '3.8',
        '3.9rem' => '3.9',
        '4rem' => '4',
        '4.1rem' => '4.1',
        '4.2rem' => '4.2',
        '4.3rem' => '4.3',
        '4.4rem' => '4.4',
        '4.5rem' => '4.5',
        '4.6rem' => '4.6',
        '4.7rem' => '4.7',
        '4.8rem' => '4.8',
        '4.9rem' => '4.9',
        '5rem' => '5',
        '5.5rem' => '5.5',
        '6rem' => '6',
    );

$font_styles = array(
        'normal' => 'normal',
        'italic' => 'italic'
    );


$font_weights = array(
        '100'=>'100',
        '200'=>'200',
        '300'=>'300',
        '400'=>'400',
        '500'=>'500',
        '600'=>'600',
        '700'=>'700',
        '800'=>'800',
        '900'=>'900',
    );
    